### ISSUE TITLE
RODO

### ISSUE THREAD

**Issue by Marcin-Drzewiczak** [AdamLewicki/flatmapp_server#1]
Użytkownik prawnie może zażądać danych jakie zgromadziliśmy o nim. Trzeba pomyśleć i zaimplementować  jak zrealizować wymagania stawiane przez EU.

**Comment by deadsmond** [comment]
1. rozpoznanie czy serwis podpada pod obsługę RODO:

Przykładowy regulamin serwisu: https://www.krafla.eu/privacy/

Opis: https://help.returnpath.com/hc/en-us/articles/115001890751-What-is-the-General-Data-Protection-Regulation-GDPR-and-how-does-it-affect-you-

lepszy opis: https://europa.eu/youreurope/business/dealing-with-customers/data-protection/data-protection-gdpr/index_en.htm

oficjalny opis: https://www.gdpreu.org/the-regulation/key-concepts/data-controllers-and-processors/

**Comment by AdamLewicki** [comment]
Serwis nie podpada pod RODO, zamykam issue
